### ISSUE TITLE
I can not install windows on top of linux

### ISSUE THREAD

**Issue by luiz8719** [feren-OS/feren-OS-Bug-Reporting#40]
I want to install windows 10 and is using both systems, but I can not install windows, I put the windows on the pendrive, but at boot it just goes through and starts linux.

How can I solve this?

**Comment by feren** [comment]
@luiz8719 Go into a Terminal, and run these commands **without quotes**:
'sudo update-grub'

Then restart, and Windows Boot Manager (Windows 10) should be an option

**Comment by luiz8719** [comment]
run this command on the terminal and reboot but it is not working !!

it is as if it skips the pendrive or does not recognize the ISO present on the pendrive !!

can you help me??

**Comment by feren** [comment]
@luiz8719 What program did you use to write Windows Pre-installation Environment to?
http://www.omgubuntu.co.uk/2017/06/create-bootable-windows-10-usb-ubuntu

From what I'm reading, that seems to be more of a PC BIOS not booting into it issue than an issue with feren OS, because the GRUB Update was to fix it for after Windows is installed...

**Comment by luiz8719** [comment]
![20171022_152412](https://user-images.githubusercontent.com/31696578/31889149-21fe1dd8-b7d5-11e7-8a79-2f9a855a684a.jpg)
está acontecendo isso! não sei o que fazer !

**Comment by feren** [comment]
1. Install Windows up to the first reboot
2. Boot into feren OS, go into a Terminal and run 'sudo update-grub'
3. Continue Windows Installation via the Windows Boot Loader option that should appear in GRUB 

Doesn't that work?

**Comment by luiz8719** [comment]
"Install Windows up to the first reboot" ,I did not understand! as?

**Comment by luiz8719** [comment]
luiz@luiz-All-Series ~ $ sudo update-grub
[sudo] senha para luiz: 
Generating grub configuration file ...
Aviso: Setting GRUB_TIMEOUT to a non-zero value when GRUB_HIDDEN_TIMEOUT is set is no longer supported.
Imagem Linux encontrada: /boot/vmlinuz-4.10.0-37-generic
Imagem initrd encontrada: /boot/initrd.img-4.10.0-37-generic
Imagem Linux encontrada: /boot/vmlinuz-4.10.0-35-generic
Imagem initrd encontrada: /boot/initrd.img-4.10.0-35-generic
Imagem Linux encontrada: /boot/vmlinuz-4.8.0-53-generic
Imagem initrd encontrada: /boot/initrd.img-4.8.0-53-generic
Found memtest86+ image: /boot/memtest86+.elf
Found memtest86+ image: /boot/memtest86+.bin
concluído
luiz@luiz-All-Series ~ $

**Comment by luiz8719** [comment]
I am running this command and restarting the computer and it is not solving

**Comment by feren** [comment]
Odd, looks like GRUB is ignoring your Windows Install, well, can't blame it, it's not like Windows doesn't like to nuke GRUB from the system half the time...

What partition is Windows on? (Install GParted, and take a screenshot of the HDD in that)

**Comment by luiz8719** [comment]
I can not install gparted

**Comment by luiz8719** [comment]
Can I do something else?

**Comment by feren** [comment]
@luiz8719 'sudo apt install gparted' from feren OS

**Comment by luiz8719** [comment]
luiz@luiz-All-Series ~ $ sudo apt install gparted
[sudo] senha para luiz: 
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
O pacote gparted não está disponível, mas é referenciado por outro pacote.
Isto pode significar que o pacote está faltando, ficou obsoleto ou
está disponível somente a partir de outra fonte

E: O pacote 'gparted' não tem candidato para instalação

**Comment by feren** [comment]
No installation candidate... :thinking: 
Hang on, let me check something...

**Comment by feren** [comment]
@luiz8719 Try downloading it from here (Choose amd64 at the bottom for x64 Bit PCs (Modern PCs), and i386 for the PCs using the x32 feren OS Version):
https://packages.ubuntu.com/xenial/gparted

Go into Terminal by going into the Folder you downloaded the file to, right-clicking on the white space in the folder/file view, and hitting Open In Terminal, followed by doing the following:
1. Type in 'sudo dpkg -i ' (without the quotes)
2. Drag the DEB into the Terminal Window, and then press ENTER to run the command (sudo password = your password)
3. If you get an error, then run 'sudo apt-get -f install' in the Terminal, and if it says it will remove 'gparted', then let me know, otherwise, confirm the operation, and GParted should be installed, having activated the correct repositories...
Odd, I've always had GParted working fine here...

**Comment by tobyjwebb** [comment]
Luiz, from your description, it sounds like the BIOS isn't set up to boot from USB.
Try inserting the USB stick and then entering the BIOS configuration (you'll have to press a key when the computer boots, before the Grub menu like in your screenshot - the key is normally one of Delete, F2, F12, F10...)
Once in the BIOS change the boot order to have the USB before harddrive.

Hope this helps,

Regards,

Toby Webb

**Comment by feren** [comment]
Ah, right, thought he ALREADY installed Windows.

**Comment by luiz8719** [comment]
luiz@luiz-All-Series ~ $ '/home/luiz/Downloads/gparted_0.25.0-1_amd64 (2).deb' 
bash: /home/luiz/Downloads/gparted_0.25.0-1_amd64 (2).deb: Permissão negada
luiz@luiz-All-Series ~ $ sudo dpkg -i '/home/luiz/Downloads/gparted_0.25.0-1_amd64 (2).deb' 
[sudo] senha para luiz: 
A seleccionar pacote anteriormente não seleccionado gparted.
(Lendo banco de dados ... 325954 ficheiros e directórios actualmente instalados.)
A preparar para desempacotar .../gparted_0.25.0-1_amd64 (2).deb ...
A descompactar gparted (0.25.0-1) ...
dpkg: problemas com dependências impedem a configuração de gparted:
 gparted depende de libparted-fs-resize0 (>= 3.1); porém:
  Pacote libparted-fs-resize0 não está instalado.

dpkg: erro ao processar o pacote gparted (--install):
 problemas de dependência - deixando desconfigurado
A processar 'triggers' para gnome-menus (3.13.3-6ubuntu3.1) ...
A processar 'triggers' para desktop-file-utils (0.22+linuxmint1) ...
A processar 'triggers' para mime-support (3.59ubuntu1) ...
A processar 'triggers' para hicolor-icon-theme (0.15-0ubuntu1) ...
A processar 'triggers' para man-db (2.7.5-1) ...
Erros foram encontrados durante o processamento de:
 gparted
luiz@luiz-All-Series ~ $ sudo apt-get -f install
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
Corrigindo dependências... Pronto
Os pacotes a seguir serão REMOVIDOS:
  gparted
0 pacotes atualizados, 0 pacotes novos instalados, 1 a serem removidos e 13 não atualizados.
1 pacotes não totalmente instalados ou removidos.
Depois desta operação, 2.015 kB de espaço em disco serão liberados.
Você quer continuar? [S/n] n
Abortar.
luiz@luiz-All-Series ~ $

**Comment by luiz8719** [comment]
Toby Webb 
Thanks for the help, but I already did it and it does not work.

**Comment by tobyjwebb** [comment]
I think I'm lost...

Luiz, did you manage to boot up Windows from the usb stick and install it
then?

Regards,

Toby

**Comment by luiz8719** [comment]
No, and as it pops up no image above, I think the problem is in GRUB

**Comment by feren** [comment]
@luiz8719 Try changing the Linux Mint and Ubuntu Repo Mirrors in Software Sources...

**Comment by tobyjwebb** [comment]
There isn't much point trying to install gparted: You can't use gparted to
resize a partition that is currently in use, for that you are going to have
to use a live usb stick.

Apart from that, you don't boot the windows install stick from inside grub,
you boot to it from the bios directly (ok, maybe you can do this last bit,
but I've never done it like that).

As an alternative to using a usb stick for the windows installation, have
you tried recording an installation DVD?

Regards,

Toby

El 30 oct. 2017 15:05, "The feren OS Dev" <notifications@github.com>
escribió:

@luiz8719 <https://github.com/luiz8719> Try changing the Linux Mint and
Ubuntu Repo Mirrors in Software Sources...

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/feren-OS/feren-OS-Bug-Reporting/issues/40#issuecomment-340453929>,
or mute the thread

**Comment by tobyjwebb** [comment]
Oh, and if you're going to resize positions, make sure the doesn't try to
suspend half way through... Happened to me a couple of days ago. =(

**Comment by luiz8719** [comment]
I have not yet tested ISO on DVD, I'm going to test but I do not think that's the problem!
